// ==========================================
// BOR JHAUZ RESTAURANT - MENU & APP DATA
// ==========================================

const defaultMenu = [
    // --- RICE (CHINESE/BENGALI) ---
    { category: "Rice", name: "Jeera Rice", price: 129 },
    { category: "Rice", name: "Veg Fried Rice", price: 99 },
    { category: "Rice", name: "Chicken Fried Rice", price: 129 },
    { category: "Rice", name: "Mushroom Fried Rice", price: 119 },
    { category: "Rice", name: "Paneer Fried Rice", price: 129 },
    { category: "Rice", name: "Egg Fried Rice", price: 129 },
    { category: "Rice", name: "Chicken Fried Rice (Alt)", price: 139 },
    { category: "Rice", name: "Schezwan Fried Rice Veg", price: 139 },
    { category: "Rice", name: "Schezwan Fried Rice Chicken", price: 169 },
    { category: "Rice", name: "Mixed Fried Rice", price: 179 },

    // --- DRY & GRAVY (CHINESE/BENGALI) ---
    { category: "Dry & Gravy", name: "Veg Manchurian Dry (8 PC)", price: 119 },
    { category: "Dry & Gravy", name: "Veg Manchurian Gravy (8 PC)", price: 139 },
    { category: "Dry & Gravy", name: "Baby Corn Dry", price: 129 },
    { category: "Dry & Gravy", name: "Chilli Chicken Dry (8 PC)", price: 139 },
    { category: "Dry & Gravy", name: "Chilli Chicken Gravy (8 PC)", price: 159 },
    { category: "Dry & Gravy", name: "Ruby Creeper Dry (8 PC)", price: 109 },
    { category: "Dry & Gravy", name: "Ruby Creeper Gravy (8 PC)", price: 119 },
    { category: "Dry & Gravy", name: "Mushroom Dry", price: 119 },
    { category: "Dry & Gravy", name: "Mushroom Gravy", price: 129 },
    { category: "Dry & Gravy", name: "Chicken Lollipop (4 PC)", price: 159 },
    { category: "Dry & Gravy", name: "Chilli Paneer Dry (8 PC)", price: 149 },
    { category: "Dry & Gravy", name: "Chilli Paneer Gravy (8 PC)", price: 169 },
    { category: "Dry & Gravy", name: "Boneless Chicken Gravy (8 PC)", price: 169 },
    { category: "Dry & Gravy", name: "Chicken Kasa (4 PC)", price: 209 },
    { category: "Dry & Gravy", name: "Kadai Chicken (4 PC)", price: 229 },
    { category: "Dry & Gravy", name: "Butter Chicken (4 PC)", price: 249 },
    { category: "Dry & Gravy", name: "Kadai Paneer (6 PC)", price: 239 },
    { category: "Dry & Gravy", name: "Butter Paneer (4 PC)", price: 259 },

    // --- OUR SPECIAL ---
    { category: "Our Special", name: "Pav Bhaji Veg", price: 69 },
    { category: "Our Special", name: "Pav Bhaji Chicken", price: 89 },
    { category: "Our Special", name: "Vada Pav", price: 59 },
    { category: "Our Special", name: "Tacos Veg", price: 179 },
    { category: "Our Special", name: "Tacos Chicken", price: 199 },
    { category: "Our Special", name: "Lasagna Veg", price: 179 },
    { category: "Our Special", name: "Lasagna Mushroom", price: 179 },
    { category: "Our Special", name: "Lasagna Chicken", price: 199 },
    { category: "Our Special", name: "Baked Cheese Nachos with Salsa Sauce", price: 179 },
    { category: "Our Special", name: "Baked Cheese Nachos with Chicken", price: 199 },
    { category: "Our Special", name: "Nachos Salsa Dip", price: 149 },
    { category: "Our Special", name: "Baked French Fries Salted", price: 79 },
    { category: "Our Special", name: "Baked French Fries Masala", price: 99 },
    { category: "Our Special", name: "Baked French Fries Peri Peri", price: 119 },
    { category: "Our Special", name: "Sha Phaley 2 pc (Chicken)", price: 89 },
    { category: "Our Special", name: "Thuppa Veg", price: 79 },
    { category: "Our Special", name: "Thuppa Egg", price: 89 },
    { category: "Our Special", name: "Thuppa Chicken", price: 99 },
    { category: "Our Special", name: "Potlam Veg", price: 189 },

    // --- SPECIAL MINIMUM WAITING 20 MINS ---
    { category: "Special (20 Mins)", name: "Veg Pokoda", price: 99 },
    { category: "Special (20 Mins)", name: "Onion Pokoda", price: 109 },
    { category: "Special (20 Mins)", name: "Paneer Pokoda (10pc)", price: 139 },
    { category: "Special (20 Mins)", name: "Egg Pokoda (2pc big)", price: 129 },
    { category: "Special (20 Mins)", name: "Chicken Kima Pokoda (8pc)", price: 159 },
    { category: "Special (20 Mins)", name: "Cheese Pokoda (8pc)", price: 179 },
    { category: "Special (20 Mins)", name: "Vetki Fish Pokoda (8pc)", price: 229 },
    { category: "Special (20 Mins)", name: "Prawns 65 (8pc)", price: 249 },
    { category: "Special (20 Mins)", name: "Chilli Prawns (8pc)", price: 239 },
    { category: "Special (20 Mins)", name: "Prawns Ghee Roast (8pc)", price: 259 },

    // --- MOMO ---
    { category: "Momo", name: "Steamed Momos Veg (8pc)", price: 59 },
    { category: "Momo", name: "Steamed Momos Chicken (8pc)", price: 79 },
    { category: "Momo", name: "Schezwan Momos Veg (8pc)", price: 99 },
    { category: "Momo", name: "Schezwan Momos Chicken (8pc)", price: 129 },
    { category: "Momo", name: "Cheese Momos Veg (8pc)", price: 139 },
    { category: "Momo", name: "Cheese Momos Chicken (8pc)", price: 159 },
    { category: "Momo", name: "Malai Momos Veg (8pc)", price: 129 },
    { category: "Momo", name: "Malai Momos Chicken (8pc)", price: 149 },
    { category: "Momo", name: "Veg Momos Fried", price: 79 },
    { category: "Momo", name: "Veg Momos Peri Peri", price: 89 },
    { category: "Momo", name: "Veg Momos Gravy", price: 99 },
    { category: "Momo", name: "Chicken Momos Fried", price: 99 },
    { category: "Momo", name: "Chicken Momos Peri Peri", price: 109 },
    { category: "Momo", name: "Chicken Momos Gravy", price: 119 },
    { category: "Momo", name: "White Sauce Momos Veg (8pc)", price: 99 },
    { category: "Momo", name: "White Sauce Momos Chicken (8pc)", price: 119 },
    { category: "Momo", name: "Red Sauce Momos Veg (8pc)", price: 99 },
    { category: "Momo", name: "Red Sauce Momos Chicken (8pc)", price: 129 },
    { category: "Momo", name: "Mayonnaise Momos Veg (8pc)", price: 99 },
    { category: "Momo", name: "Mayonnaise Momos Chicken (8pc)", price: 139 },
    { category: "Momo", name: "Kurkure Momos Veg (8pc)", price: 129 },
    { category: "Momo", name: "Kurkure Momos Chicken (8pc)", price: 139 },
    { category: "Momo", name: "Typhoo (1 Pc)", price: 79 },

    // --- PIZZA ---
    { category: "Pizza", name: "Margherita Pizza Small", price: 89 },
    { category: "Pizza", name: "Margherita Pizza Large", price: 149 },
    { category: "Pizza", name: "OTC Pizza Small", price: 109 },
    { category: "Pizza", name: "OTC Pizza Large", price: 149 },
    { category: "Pizza", name: "Onion Pizza Small", price: 99 },
    { category: "Pizza", name: "Onion Pizza Large", price: 149 },
    { category: "Pizza", name: "Mushroom Pizza Small", price: 119 },
    { category: "Pizza", name: "Mushroom Pizza Large", price: 179 },
    { category: "Pizza", name: "Golden Corn Pizza Small", price: 149 },
    { category: "Pizza", name: "Golden Corn Pizza Large", price: 199 },
    { category: "Pizza", name: "Garden Pizza Small", price: 159 },
    { category: "Pizza", name: "Garden Pizza Large", price: 209 },
    { category: "Pizza", name: "Veg Unanza Pizza Small", price: 179 },
    { category: "Pizza", name: "Veg Unanza Pizza Large", price: 249 },
    { category: "Pizza", name: "Paneer Pizza Small", price: 169 },
    { category: "Pizza", name: "Paneer Pizza Large", price: 209 },
    { category: "Pizza", name: "Peri Peri Paneer Pizza Small", price: 189 },
    { category: "Pizza", name: "Peri Peri Paneer Pizza Large", price: 219 },
    { category: "Pizza", name: "Chicken Pizza Small", price: 159 },
    { category: "Pizza", name: "Chicken Pizza Large", price: 239 },
    { category: "Pizza", name: "Special Double Chicken Pizza Small", price: 189 },
    { category: "Pizza", name: "Special Double Chicken Pizza Large", price: 279 },
    { category: "Pizza", name: "Spicy Chicken Pizza Small", price: 179 },
    { category: "Pizza", name: "Spicy Chicken Pizza Large", price: 279 },

    // --- NOODLES ---
    { category: "Noodles", name: "Plain Maggi", price: 39 },
    { category: "Noodles", name: "Masala Maggi", price: 49 },
    { category: "Noodles", name: "Veggie Maggi", price: 59 },
    { category: "Noodles", name: "Veggie Cheese Maggi", price: 79 },
    { category: "Noodles", name: "Hakka Noodles", price: 59 },
    { category: "Noodles", name: "Noodles Veg", price: 69 },
    { category: "Noodles", name: "Noodles Mushroom", price: 79 },
    { category: "Noodles", name: "Noodles Egg", price: 79 },
    { category: "Noodles", name: "Noodles Chicken", price: 89 },
    { category: "Noodles", name: "Chilli Garlic Noodles Veg", price: 79 },
    { category: "Noodles", name: "Chilli Garlic Noodles Mushroom", price: 89 },
    { category: "Noodles", name: "Chilli Garlic Noodles Egg", price: 89 },
    { category: "Noodles", name: "Chilli Garlic Noodles Chicken", price: 99 },
    { category: "Noodles", name: "Egg & Chicken Noodles", price: 109 },
    { category: "Noodles", name: "Schezwan Noodles Veg", price: 79 },
    { category: "Noodles", name: "Schezwan Noodles Chicken", price: 99 },
    { category: "Noodles", name: "Chinese Bhel", price: 59 },
    { category: "Noodles", name: "Kurkure Bhel Veg", price: 49 },
    { category: "Noodles", name: "Kurkure Bhel Chicken", price: 69 },
    { category: "Noodles", name: "Singapore Noodles Veg", price: 99 },
    { category: "Noodles", name: "Singapore Noodles Chicken", price: 119 },
    { category: "Noodles", name: "Hong Kong Noodles Veg", price: 99 },
    { category: "Noodles", name: "Hong Kong Noodles Chicken", price: 119 },

    // --- PASTA ---
    { category: "Pasta", name: "White Sauce Pasta", price: 159 },
    { category: "Pasta", name: "Red Sauce Pasta", price: 149 },
    { category: "Pasta", name: "Mix Sauce Pasta", price: 169 },
    { category: "Pasta", name: "Spaghetti Pasta", price: 169 },

    // --- SOUTH INDIAN ---
    { category: "South Indian", name: "Idli (2pc)", price: 39 },
    { category: "South Indian", name: "Plain Dosa", price: 59 },
    { category: "South Indian", name: "Masala Dosa", price: 79 },
    { category: "South Indian", name: "Masala Cheese Dosa", price: 99 },
    { category: "South Indian", name: "Paneer Dosa", price: 119 },
    { category: "South Indian", name: "Masala Panner Dosa", price: 129 },
    { category: "South Indian", name: "Onion Dosa", price: 69 },
    { category: "South Indian", name: "Medu Vada", price: 49 },

    // --- TEA / BEVERAGES ---
    { category: "Tea & Beverages", name: "Normal Tea Small", price: 15 },
    { category: "Tea & Beverages", name: "Normal Tea Large", price: 29 },
    { category: "Tea & Beverages", name: "Masala Tea Small", price: 19 },
    { category: "Tea & Beverages", name: "Masala Tea Large", price: 29 },
    { category: "Tea & Beverages", name: "Green Tea", price: 15 },
    { category: "Tea & Beverages", name: "Lemon Tea or Black", price: 19 },
    { category: "Tea & Beverages", name: "Tanduri Tea", price: 29 },
    { category: "Tea & Beverages", name: "Elaichi Tea Small", price: 19 },
    { category: "Tea & Beverages", name: "Elaichi Tea Large", price: 29 },
    { category: "Tea & Beverages", name: "Lemon Ice Tea", price: 59 },
    { category: "Tea & Beverages", name: "Peach Ice Tea", price: 59 },
    { category: "Tea & Beverages", name: "Mint Ice Tea", price: 59 },

    // --- COFFEE ---
    { category: "Coffee", name: "Hot Coffee", price: 29 },
    { category: "Coffee", name: "Black Coffee", price: 25 },
    { category: "Coffee", name: "Cappuccino", price: 39 },
    { category: "Coffee", name: "Latte", price: 39 },
    { category: "Coffee", name: "Cold Coffee", price: 99 },

    // --- LASSI ---
    { category: "Lassi", name: "Sweet Lassi", price: 69 },
    { category: "Lassi", name: "Masala Lassi", price: 79 },
    { category: "Lassi", name: "Mango Lassi", price: 99 },

    // --- MILK SHAKE ---
    { category: "Milk Shake", name: "Choco Shake", price: 99 },
    { category: "Milk Shake", name: "Strawberry Shake", price: 99 },
    { category: "Milk Shake", name: "Oreo Shake", price: 99 },
    { category: "Milk Shake", name: "Kitkat Shake", price: 99 },
    { category: "Milk Shake", name: "Chocolate Shake", price: 99 },
    { category: "Milk Shake", name: "Mango Shake", price: 99 },
    { category: "Milk Shake", name: "Butterscotch Shake", price: 99 },
    { category: "Milk Shake", name: "Vanilla Shake", price: 89 },

    // --- MOCKTAILS & DRINKS ---
    { category: "Mocktails & Drinks", name: "Lemon Mint Mojito", price: 79 },
    { category: "Mocktails & Drinks", name: "Blue Lagoon", price: 79 },
    { category: "Mocktails & Drinks", name: "Watermelon Mojito", price: 79 },
    { category: "Mocktails & Drinks", name: "Black Currant Mojito", price: 69 },
    { category: "Mocktails & Drinks", name: "Lychee Mojito", price: 69 },
    { category: "Mocktails & Drinks", name: "Ripe Mango Mojito", price: 69 },
    { category: "Mocktails & Drinks", name: "Mango Mule", price: 109 },
    { category: "Mocktails & Drinks", name: "Masala Coke", price: 49 },
    { category: "Mocktails & Drinks", name: "Masala Sprite", price: 49 },
    { category: "Mocktails & Drinks", name: "Aam Panna", price: 49 },
    { category: "Mocktails & Drinks", name: "Fresh Lemon Soda", price: 39 },
    { category: "Mocktails & Drinks", name: "Masala Shikanji", price: 39 },
    { category: "Mocktails & Drinks", name: "Spicy Lime Soda", price: 69 },
    { category: "Mocktails & Drinks", name: "Cold Drink", price: 40 },

    // --- SOUP ---
    { category: "Soup", name: "Sweet Corn Soup", price: 49 },
    { category: "Soup", name: "Cream of Tomato Soup", price: 49 },
    { category: "Soup", name: "Cream of Mushroom Soup", price: 59 },
    { category: "Soup", name: "Hot & Sour Soup Veg", price: 69 },
    { category: "Soup", name: "Hot & Sour Soup Chicken", price: 89 },
    { category: "Soup", name: "Manchow Soup Veg", price: 69 },
    { category: "Soup", name: "Manchow Soup Chicken", price: 89 },
    { category: "Soup", name: "Minestrone Soup", price: 69 },
    { category: "Soup", name: "Lung Fung Soup Chicken", price: 79 },
    { category: "Soup", name: "Clear Soup", price: 49 },

    // --- VEG SNACKS ---
    { category: "Veg Snacks", name: "French Fries Salted", price: 59 },
    { category: "Veg Snacks", name: "French Fries Masala", price: 69 },
    { category: "Veg Snacks", name: "French Fries Peri Peri", price: 79 },
    { category: "Veg Snacks", name: "Smilies (8 Pcs)", price: 59 },
    { category: "Veg Snacks", name: "Veg Nuggets (8 Pcs)", price: 99 },
    { category: "Veg Snacks", name: "Spicy Potato Tikki (2 Pcs)", price: 89 },
    { category: "Veg Snacks", name: "Paneer 65 (8 Pcs)", price: 159 },
    { category: "Veg Snacks", name: "Baby Corn Fritters", price: 109 },
    { category: "Veg Snacks", name: "Chilli Garlic Nuggets (8 Pcs)", price: 99 },
    { category: "Veg Snacks", name: "Baby Corn Dry Fry (8 Pcs)", price: 119 },
    { category: "Veg Snacks", name: "Honey Chilli Potato", price: 119 },
    { category: "Veg Snacks", name: "American Crispy Corn", price: 99 },
    { category: "Veg Snacks", name: "Corn Chat", price: 99 },
    { category: "Veg Snacks", name: "Paneer Ball (8 Pcs)", price: 169 },

    // --- CHICKEN SNACKS ---
    { category: "Chicken Snacks", name: "Chicken Leg (2PC) KFC style", price: 179 },
    { category: "Chicken Snacks", name: "Chicken Popcorn (8pc)", price: 109 },
    { category: "Chicken Snacks", name: "Chicken Pakora (8pc)", price: 129 },
    { category: "Chicken Snacks", name: "Dragon Chicken", price: 149 },
    { category: "Chicken Snacks", name: "Kimchi Chicken (5pc)", price: 149 },
    { category: "Chicken Snacks", name: "Chicken 65 (8pc)", price: 139 },
    { category: "Chicken Snacks", name: "Chicken Lollipop (4pc)", price: 139 },
    { category: "Chicken Snacks", name: "Chilli Chicken (8pc)", price: 139 },
    { category: "Chicken Snacks", name: "Honey Chilli Chicken", price: 149 },
    { category: "Chicken Snacks", name: "Chicken Masala Nugget (8pc)", price: 119 },
    { category: "Chicken Snacks", name: "Chicken Finger (5pc)", price: 119 },
    { category: "Chicken Snacks", name: "Chicken Fry (4pc)", price: 139 },
    { category: "Chicken Snacks", name: "Fish Finger (4pc)", price: 99 },
    { category: "Chicken Snacks", name: "Chicken Dry Fry (4pc)", price: 129 },

    // --- ROLLS ---
    { category: "Rolls", name: "Spring Roll Veg", price: 69 },
    { category: "Rolls", name: "Spring Roll Chicken", price: 79 },
    { category: "Rolls", name: "Roll Veg", price: 69 },
    { category: "Rolls", name: "Roll Egg", price: 79 },
    { category: "Rolls", name: "Roll Paneer", price: 89 },
    { category: "Rolls", name: "Roll Chicken", price: 99 },
    { category: "Rolls", name: "Single Egg Chicken Roll", price: 109 },
    { category: "Rolls", name: "Double Egg Chicken Roll", price: 129 },
    { category: "Rolls", name: "Chilli Chicken Roll", price: 129 },
    { category: "Rolls", name: "Paneer Roll", price: 119 },

    // --- SANDWICH ---
    { category: "Sandwich", name: "Veg Cold Cheese Sandwich", price: 49 },
    { category: "Sandwich", name: "Punjabi Sandwich", price: 59 },
    { category: "Sandwich", name: "Veg Grilled Sandwich", price: 69 },
    { category: "Sandwich", name: "Veg Cheese Grilled Sandwich", price: 79 },
    { category: "Sandwich", name: "Indian Paneer Sandwich", price: 79 },
    { category: "Sandwich", name: "Chicken Sandwich", price: 79 },

    // --- BURGER ---
    { category: "Burger", name: "Crispy Veggie Burger", price: 69 },
    { category: "Burger", name: "Herb Chilli Burger", price: 69 },
    { category: "Burger", name: "Veggie Cheese Burger", price: 79 },
    { category: "Burger", name: "Crispy Chicken Burger", price: 89 },
    { category: "Burger", name: "Chicken Cheese Burger", price: 99 },
    { category: "Burger", name: "Maharaja Veg Burger", price: 109 },
    { category: "Burger", name: "Maharaja Chicken Burger", price: 129 },

    // --- GARLIC BREAD ---
    { category: "Garlic Bread", name: "Plain Garlic Bread", price: 69 },
    { category: "Garlic Bread", name: "Cheese Garlic Bread", price: 89 },
    { category: "Garlic Bread", name: "Bruschetta", price: 89 },

    // --- WATER ---
    { category: "Water", name: "Packaged Drinking Water (500ml)", price: 10 },
    { category: "Water", name: "Packaged Drinking Water (1L)", price: 20 }
];
